#!/bin/bash

#ProgressBar function
_progress=0
_end=100
function ProgressBar {
   let _progress=(${1}*100/${2}*100)/100
   let _done=(${_progress}*4)/10
   let _left=40-$_done
   _fill=$(printf "%${_done}s")
   _empty=$(printf "%${_left}s")
   printf "%b\n\rProgress : [${_fill// /#}${_empty// /-}] ${_progress}%%"
}

#Colors
_green='\033[0;32m'
_yellow='\033[0;33m'
_blue='\033[0;34m'
_clear='\033[0m'

_avail_disk_space=$(df -H / --output=avail)
echo -e "${_yellow}Available disk space now${_clear}:\n${_blue}$avail_disk_space${_clear}\n"

#Installing docker
echo -e "${_yellow}Installing docker${_clear}...\n"
_progress=9
ProgressBar "${_progress}" "${_end}"
sleep 2
sudo apt update
if sudo apt install docker docker-compose
then
_doc_ver=$(docker --version)
echo -e "${_green}Docker successfully installed with version${_clear}:\n${_blue}$_doc_ver${_clear}\n"
fi

#Installing php-modules, php and node + npm
echo -e "${_yellow}Installing php-modules, php and node + npm${_clear}...\n"
_progress=20
ProgressBar "$_progress" "$_end"
sleep 2
sudo apt install software-properties-common
sudo add-apt-repository ppa:ondrej/php
sudo apt update
if sudo apt install php7.4 php7.4-{common,xml,mbstring,zip,curl,http,pdo,pgsql,memcached,gd,xdebug} nodejs npm;
then
_php_ver=$(php --version)
_node_ver=$(node -v)
echo -e "${_green}PHP successfully installed with version${_clear}:\n${_blue}$_php_ver${_clear}"
echo -e "${_green}Nodejs successfully installed with version${_clear}:\n${_blue}$_node_ver${_clear}\n"
fi

#Installing golang
echo -e "${_yellow}Installing golang${_clear}...\n"
_progress=41
ProgressBar "${_progress}" "${_end}"
sleep 2
sudo apt update
sudo apt upgrade
sudo apt search golang-go
sudo apt search gccgo-go
if sudo apt install golang-go
then
echo -e "${_green}Golang successfully installed!${_clear}\n"
fi

#Installing gnome-tweaks
echo -e "${_yellow}Installing gnome-tweaks${_clear}...\n"
_progress=55
ProgressBar "${_progress}" "${_end}"
sleep 2
sudo apt update
if sudo apt install gnome-tweaks
then
echo -e "${_green}Gnome-tweaks successfully installed${_clear}!\n"
fi

#Installing openvpn
echo -e "${_yellow}Installing openvpn${_clear}...\n"
_progress=68
ProgressBar "${_progress}" "${_end}"
sleep 2
sudo apt update
sudo apt install apt-transport-https
if sudo apt install openvpn
then
echo -e "${_green}Openvpn successfully installed${_clear}!\n"
echo -e "${_yellow}Generating static openvpn key${_clear}...\n"
_progress=82
ProgressBar "${_progress}" "${_end}"
sleep 2
if openvpn --genkey --secret static-OpenVPN.key
then
echo -e "${_green}Secret static key successfully generated${_clear}!\n"
fi
fi

#Installing codecs and fonts
echo -e "${_yellow}Installing codecs and fonts${_clear}...\n"
_progress=90
ProgressBar "${_progress}" "${_end}"
sleep 2
sudo apt update
if sudo apt install ubuntu-restricted-extras
then
echo -e "${_green}Codecs and fonts successfully installed${_clear}!\n"
fi

echo "${_green}Installation successfully completed${_clear}!"
